# http://docs.travis-ci.com/user/build-configuration/
language: cpp
compiler:
  - gcc
  - clang
#branches:
#  only:
#    - master
before_install:
  - sudo apt-get update -qq # UPDATE REPOS
  - sudo mk/linux/setupBuildDeps.sh --quiet # INSTALL DEPENDENCIES HERE
script:
# ALL THE BUILD COMMANDS HERE
  - mk/linux/build-mg.sh -c 4
notifications:
  irc:
    channels:
      - "irc.freenode.org#megaglest"
    skip_join: true
    use_notice: true
    template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      - "[%{repository}#%{branch} @%{commit}] %{author}): %{message}"
      - "Diff: %{compare_url}"
      - "Build: %{build_url}"
